{% set name = 'clingo' %}

package:
  name: {{ name }}
  version: 5.3.0

source:
  git_rev: backend
  git_url: https://github.com/potassco/{{ name }}.git

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vc >=14 [win]
    - python
  run:
    - python

build:
  number: 2

test:
  commands:
    - clingo --version
    - clasp --version
    - reify --version
    - lpconvert --version
    - gringo --version

about:
  home:  https://potassco.org/
  license: MIT
  summary: A grounder and solver for logic programs.
  description: Clingo is an answer set programming (ASP) system that takes a logic program as input and calculates its answer sets.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}
