[tool.cibuildwheel]
python-versions = ["pp310", "pp311", "cp310"]

[tool.cibuildwheel.config-settings]
skbuild.cmake.define.PYBIND11_STABLE_ABI = "ON"

[tool.cibuildwheel.linux]
archs = ["x86_64", "i686", "aarch64", "ppc64le", "musllinux_x86_64", "musllinux_i686"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.windows]
archs = ["x86_64", "x86"]

[tool.cibuildwheel.pyodide]
python-versions = ["cp313"]
