[project]
name = "clingo"
version = "6.0.0"

[project.scripts]
pyclingo = "clingo.app:_pyclingo"

[build-system]
requires = ["scikit-build-core", "pybind11", "re2c"]
build-backend = "scikit_build_core.build"

[tool.scikit-build.sdist]
include = ["lib/*", "third_party/*", "app/*", "CMakeLists.txt"]
exclude = ["*.pyc"]

[tool.scikit-build.wheel]
# TODO: install components are the cleaner way to implement this
exclude = ["include/amc/*", "bin/*", "share/*"]

[tool.pytest.ini_options]
addopts = [
    "--ignore=third_party",
    "--ignore=doc",
    "--ignore=.git",
]
testpaths = ["lib"]

[tool.ruff]
ignore = ["E741"]

[tool.pylint.design]
min-public-methods = 1
