# DO NOT EDIT THIS FILE! It was generated by scratch/mypy.py.

from typing import *
from abc import *

from .types import Comparable
from . import ast




def Aggregate(*args: Any, **kwargs: Any) -> Any: ...
def AggregateGuard(*args: Any, **kwargs: Any) -> Any: ...
def BinaryOperation(*args: Any, **kwargs: Any) -> Any: ...
def BodyAggregate(*args: Any, **kwargs: Any) -> Any: ...
def BodyAggregateElement(*args: Any, **kwargs: Any) -> Any: ...
def BooleanConstant(*args: Any, **kwargs: Any) -> Any: ...
def CSPGuard(*args: Any, **kwargs: Any) -> Any: ...
def CSPLiteral(*args: Any, **kwargs: Any) -> Any: ...
def CSPProduct(*args: Any, **kwargs: Any) -> Any: ...
def CSPSum(*args: Any, **kwargs: Any) -> Any: ...
def Comparison(*args: Any, **kwargs: Any) -> Any: ...
def ConditionalLiteral(*args: Any, **kwargs: Any) -> Any: ...
def Defined(*args: Any, **kwargs: Any) -> Any: ...
def Definition(*args: Any, **kwargs: Any) -> Any: ...
def Disjoint(*args: Any, **kwargs: Any) -> Any: ...
def DisjointElement(*args: Any, **kwargs: Any) -> Any: ...
def Disjunction(*args: Any, **kwargs: Any) -> Any: ...
def Edge(*args: Any, **kwargs: Any) -> Any: ...
def External(*args: Any, **kwargs: Any) -> Any: ...
def Function(*args: Any, **kwargs: Any) -> Any: ...
def HeadAggregate(*args: Any, **kwargs: Any) -> Any: ...
def HeadAggregateElement(*args: Any, **kwargs: Any) -> Any: ...
def Heuristic(*args: Any, **kwargs: Any) -> Any: ...
def Id(*args: Any, **kwargs: Any) -> Any: ...
def Interval(*args: Any, **kwargs: Any) -> Any: ...
def Literal(*args: Any, **kwargs: Any) -> Any: ...
def Minimize(*args: Any, **kwargs: Any) -> Any: ...
def Pool(*args: Any, **kwargs: Any) -> Any: ...
def Program(*args: Any, **kwargs: Any) -> Any: ...
def ProjectAtom(*args: Any, **kwargs: Any) -> Any: ...
def ProjectSignature(*args: Any, **kwargs: Any) -> Any: ...
def Rule(*args: Any, **kwargs: Any) -> Any: ...
def Script(*args: Any, **kwargs: Any) -> Any: ...
def ShowSignature(*args: Any, **kwargs: Any) -> Any: ...
def ShowTerm(*args: Any, **kwargs: Any) -> Any: ...
def Symbol(*args: Any, **kwargs: Any) -> Any: ...
def SymbolicAtom(*args: Any, **kwargs: Any) -> Any: ...
def TheoryAtom(*args: Any, **kwargs: Any) -> Any: ...
def TheoryAtomDefinition(*args: Any, **kwargs: Any) -> Any: ...
def TheoryAtomElement(*args: Any, **kwargs: Any) -> Any: ...
def TheoryDefinition(*args: Any, **kwargs: Any) -> Any: ...
def TheoryFunction(*args: Any, **kwargs: Any) -> Any: ...
def TheoryGuard(*args: Any, **kwargs: Any) -> Any: ...
def TheoryGuardDefinition(*args: Any, **kwargs: Any) -> Any: ...
def TheoryOperatorDefinition(*args: Any, **kwargs: Any) -> Any: ...
def TheorySequence(*args: Any, **kwargs: Any) -> Any: ...
def TheoryTermDefinition(*args: Any, **kwargs: Any) -> Any: ...
def TheoryUnparsedTerm(*args: Any, **kwargs: Any) -> Any: ...
def TheoryUnparsedTermElement(*args: Any, **kwargs: Any) -> Any: ...
def UnaryOperation(*args: Any, **kwargs: Any) -> Any: ...
def Variable(*args: Any, **kwargs: Any) -> Any: ...


class AST:
    def __init__(self, type: ASTType, **arguments: Mapping[str,Any]): ...
    def items(self) -> List[Tuple[str,AST]]: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[AST]: ...
    child_keys: List[str]
    type: ASTType

class ASTType(metaclass=ABCMeta):
    Aggregate: ASTType
    AggregateGuard: ASTType
    BinaryOperation: ASTType
    BodyAggregate: ASTType
    BodyAggregateElement: ASTType
    BooleanConstant: ASTType
    CSPGuard: ASTType
    CSPLiteral: ASTType
    CSPProduct: ASTType
    CSPSum: ASTType
    Comparison: ASTType
    ConditionalLiteral: ASTType
    Defined: ASTType
    Definition: ASTType
    Disjoint: ASTType
    DisjointElement: ASTType
    Disjunction: ASTType
    Edge: ASTType
    External: ASTType
    Function: ASTType
    HeadAggregate: ASTType
    HeadAggregateElement: ASTType
    Heuristic: ASTType
    Id: ASTType
    Interval: ASTType
    Literal: ASTType
    Minimize: ASTType
    Pool: ASTType
    Program: ASTType
    ProjectAtom: ASTType
    ProjectSignature: ASTType
    Rule: ASTType
    Script: ASTType
    ShowSignature: ASTType
    ShowTerm: ASTType
    Symbol: ASTType
    SymbolicAtom: ASTType
    TheoryAtom: ASTType
    TheoryAtomDefinition: ASTType
    TheoryAtomElement: ASTType
    TheoryDefinition: ASTType
    TheoryFunction: ASTType
    TheoryGuard: ASTType
    TheoryGuardDefinition: ASTType
    TheoryOperatorDefinition: ASTType
    TheorySequence: ASTType
    TheoryTermDefinition: ASTType
    TheoryUnparsedTerm: ASTType
    TheoryUnparsedTermElement: ASTType
    UnaryOperation: ASTType
    Variable: ASTType

class AggregateFunction(Hashable, Comparable, metaclass=ABCMeta):
    Count: AggregateFunction
    Max: AggregateFunction
    Min: AggregateFunction
    Sum: AggregateFunction
    SumPlus: AggregateFunction

class BinaryOperator(metaclass=ABCMeta):
    And: BinaryOperator
    Division: BinaryOperator
    Minus: BinaryOperator
    Modulo: BinaryOperator
    Multiplication: BinaryOperator
    Or: BinaryOperator
    Plus: BinaryOperator
    Power: BinaryOperator
    XOr: BinaryOperator

class ComparisonOperator(Hashable, Comparable, metaclass=ABCMeta):
    Equal: ComparisonOperator
    GreaterEqual: ComparisonOperator
    GreaterThan: ComparisonOperator
    LessEqual: ComparisonOperator
    LessThan: ComparisonOperator
    NotEqual: ComparisonOperator

class ScriptType(metaclass=ABCMeta):
    Lua: ScriptType
    Python: ScriptType

class Sign(metaclass=ABCMeta):
    DoubleNegation: Sign
    Negation: Sign
    NoSign: Sign

class TheoryAtomType(metaclass=ABCMeta):
    Any: TheoryAtomType
    Body: TheoryAtomType
    Directive: TheoryAtomType
    Head: TheoryAtomType

class TheoryOperatorType(metaclass=ABCMeta):
    BinaryLeft: TheoryOperatorType
    BinaryRight: TheoryOperatorType
    Unary: TheoryOperatorType

class TheorySequenceType(metaclass=ABCMeta):
    List: TheorySequenceType
    Set: TheorySequenceType
    Tuple: TheorySequenceType
    left_hand_side: str
    right_hand_side: str

class UnaryOperator(metaclass=ABCMeta):
    Absolute: UnaryOperator
    Minus: UnaryOperator
    Negation: UnaryOperator
    left_hand_side: str
    right_hand_side: str
