add_subdirectory(util)
add_subdirectory(core)
add_subdirectory(input)
add_subdirectory(ground)
add_subdirectory(output)
add_subdirectory(control)
add_subdirectory(c-api)
add_subdirectory(cxx-api)
if (NOT CLINGO_BUILD_WEB)
    add_subdirectory(python-api)
else()
    add_library(clingo_python_embed INTERFACE)
    add_library(clingo::python ALIAS clingo_python_embed)
endif()
