add_library(gringo_util INTERFACE)

target_link_libraries(gringo_util INTERFACE tsl::hopscotch_map tsl::ordered_map)
target_include_directories(gringo_util INTERFACE "include")
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    target_compile_options(gringo_util INTERFACE "-Wno-zero-length-array")
endif()
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_compile_options(gringo_util INTERFACE "-Wno-pedantic")
endif()
