/* Generated by re2c 3.1 on Tue Jan 27 10:20:47 2026 */

#line 4 "/home/runner/work/clingo/clingo/_codeql_build_dir/libclingo/input/src/parse/lexer_impl_h.hh"
#define YYMAXFILL 11
#line 57 "/home/runner/work/clingo/clingo/lib/input/src/parse/lexer_impl.xch"

#line 8 "/home/runner/work/clingo/clingo/_codeql_build_dir/libclingo/input/src/parse/lexer_impl_h.hh"
enum YYCONDTYPE {
	yycprogram,
	yycnormal,
	yyctheory,
	yycinclude,
	yycfstring_spec,
	yycfstring,
	yycscript,
	yycblockcomment
};
#line 58 "/home/runner/work/clingo/clingo/lib/input/src/parse/lexer_impl.xch"

