FIND_PROGRAM (RE2C_EXECUTABLE NAMES re2c)

IF (RE2C_EXECUTABLE)
	SET(RE2C_FOUND TRUE)
ENDIF (RE2C_EXECUTABLE)

IF (RE2C_FOUND)
	IF (NOT RE2C_FIND_QUIETLY)
		MESSAGE(STATUS "Looking for re2c... - found ${RE2C_EXECUTABLE}")
	ENDIF (NOT RE2C_FIND_QUIETLY)
ELSE (RE2C_FOUND)
	IF (RE2C_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Looking for re2c... - NOT found")
	ENDIF (RE2C_FIND_REQUIRED)
	MESSAGE(STATUS "Looking for re2c... - NOT found")
ENDIF (RE2C_FOUND)

