function(re2c_target_or_gen GRAMMAR)
    get_filename_component(directory "${GRAMMAR}" DIRECTORY)
    get_filename_component(filename "${GRAMMAR}" NAME_WE)
    get_filename_component(extension "${GRAMMAR}" EXT)
    set(bin_path "${CMAKE_CURRENT_BINARY_DIR}/${directory}")
    set(gen_path "${CMAKE_CURRENT_SOURCE_DIR}/gen/${directory}")
    file(MAKE_DIRECTORY "${bin_path}")
    if(RE2C_FOUND)
        if (extension STREQUAL ".xch")
            re2c_target(NAME ${filename} INPUT "${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR}" OUTPUT "${bin_path}/${filename}.hh" OPTIONS -c)
        else()
            re2c_target(NAME ${filename} INPUT "${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR}" OUTPUT "${bin_path}/${filename}.hh")
        endif()
        set("RE2C_${filename}_OUTPUT" ${RE2C_${filename}_OUTPUT} PARENT_SCOPE)
        # add to gen target
        add_custom_target("gen${gen_count}" DEPENDS "${bin_path}/${filename}.hh")
        add_dependencies(gen "gen${gen_count}")
        math(EXPR gen_count "${gen_count}+1")
        set(gen_count "${gen_count}" PARENT_SCOPE)
    elseif (EXISTS "${gen_path}/${filename}.hh")
        file(COPY "${gen_path}/${filename}.hh" DESTINATION "${bin_path}")
        set("RE2C_${filename}_OUTPUT" "${bin_path}/${filename}.hh" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "re2c lexer generator required but not found")
    endif()
endfunction()
