name: Deploy pip source package (wip)

on:
  workflow_dispatch:

jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get install python3 python3-pip
        pip3 install --user --upgrade --force-reinstall pip
        python3 -m pip install --user --upgrade setuptools wheel
        sudo apt-get install bison re2c gcc g++ cmake ninja-build
        python3 -m pip install --user --upgrade scikit-build
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build source package
      run: python3 .github/pipsource.py
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist/
        repository_url: https://test.pypi.org/legacy/
