name: Deploy windows wheels (wip)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2016
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install prerequisites
      run: |
        choco install re2c
        choco install winflexbison3
        pip install --user cffi scikit-build cmake ninja twine

    - name: Compile clingo
      run: python .github/pipwindows.py
      env:
        TWINE_NON_INTERACTIVE: True
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
